### ISSUE TITLE
Add target for installing latest build from latest release branch

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/get.submariner.io#23]
When something breaks in a release, the upgrade job on devel will continue to fail even after it's fixed in the release branch. This is because the upgrade job uses `curl -L get.submariner.io | VERSION=latest bash`, which gives the latest release but not any updates to that release branch, to install `subctl` for the first deploy.

We have the `release-0.12` and similar targets to install the latest build from some release branch, but if we use that in CI it would need to be updated for each release. Better to add a stable get.submariner.io target to get this "latest build from latest release branch".

**Comment by dfarrell07** [comment]
If we add this target, I think it would make sense to run the current `subctl latest` upgrade job periodic-only and using this new `subctl latest-prerelease` in PR-triggered CI.

**Comment by nyechiel** [comment]
@dfarrell07 can we move it out from 0.13?
