### ISSUE TITLE
Installs of devel subctl fail

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/get.submariner.io#40]
In CI and locally, installs of subctl devel using get.submariner.io fail with:

```
$ curl -L get.submariner.io | VERSION=devel bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4923    0  4923    0     0  11810      0 --:--:-- --:--:-- --:--:-- 11810
Installing subctl version devel
  OS detected:           linux
  Architecture detected: amd64
  Download URL:          https://github.com/submariner-io/subctl/releases/download/subctl-devel/subctl-devel-linux-amd64.tar.xz

Downloading...
Download attempt #1...
curl: (22) The requested URL returned error: 404
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Non-devel versions still work.

It seems [recent subctl devel builds](https://github.com/submariner-io/subctl/releases/) have a different URL than expected.

Current:

> https://github.com/submariner-io/subctl/releases/download/untagged-2c8c573f3c3380d15281/subctl-devel-linux-amd64.tar.xz

Expected:

> https://github.com/submariner-io/subctl/releases/download/subctl-devel/subctl-devel-linux-amd64.tar.xz

**Comment by skitt** [comment]
The relevant action is https://github.com/submariner-io/subctl/actions/workflows/release_subctl_on_push.yml

The [last run](https://github.com/submariner-io/subctl/actions/runs/4469043516/jobs/7850602389) deleted the old `subctl-devel` tag but doesn’t appear to have correctly created the new release. If we merge https://github.com/submariner-io/subctl/pull/618 the release will run again and hopefully do everything it’s supposed to.

**Comment by skitt** [comment]
This is now fixed.
